set(SOURCES
	src/main.cpp
	src/RenderUtilities.cpp
	src/ScopeCamera.cpp
	src/D3DHooks.cpp
	src/NiFLoader.cpp
	src/UI/ImGuiManager.cpp
	src/UI/Panels/CameraAdjustmentPanel.cpp
	src/UI/Panels/DebugPanel.cpp
	src/UI/Panels/ModelSwitcherPanel.cpp
	src/UI/Panels/SettingsPanel.cpp
	src/UI/Panels/ReticlePanel.cpp
	src/UI/Panels/ZoomDataPanel.cpp
	src/UI/Panels/PostProcessPanel.cpp
	#src/UI/Panels/PerformancePanel.cpp
	src/UI/Localization/LocalizationManager.cpp
	src/EventHandler.cpp
	src/DataPersistence.cpp
	src/DDSTextureLoader11.cpp
	src/HLSL/TrueScopeShader.hlsl
	src/HookManager.cpp
	src/TAAHook.cpp
	src/RenderHooks.cpp
	src/SimpleHooks.cpp
	#src/RenderOptimization.cpp
	src/rendering/RenderStateManager.cpp
	src/rendering/LightBackupSystem.cpp
	src/rendering/SecondPassRenderer.cpp
	src/rendering/ThermalVisionControl.cpp
	src/rendering/ThermalVision.cpp
	src/rendering/TemperatureDetection.cpp
	src/rendering/ScopeHDR.cpp
	src/rendering/BloomPass.cpp
	src/rendering/DOFPass.cpp
	src/rendering/ScopePostProcess.cpp
	src/rendering/LUTPass.cpp
	src/rendering/LuminancePass.cpp
	src/rendering/ScopeRenderingManager.cpp
	src/ImageSpaceDebugHook.cpp
	src/HDRStateCache.cpp
)
	
	
